/* Auto-generated by cbindgen. Do not edit manually. */

#ifndef LICENSE_H
#define LICENSE_H

#pragma once

/* Warning: this file is generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t license_generate(const char *product_name,
                         const char *issuance_type,
                         const char *reissue_reason,
                         const char *license_key,
                         const char *domain,
                         const char *issued_at,
                         const char *expires_at,
                         const char *license_version,
                         const char *private_key,
                         char *out_buf,
                         uintptr_t out_buf_len,
                         uintptr_t *out_written);

#endif  /* LICENSE_H */
