/* Auto-generated by cbindgen. Do not edit manually. */

#ifndef LICENSE_H
#define LICENSE_H

#pragma once

/* Warning: this file is generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t license_verify(const char *license_data, const char *public_key);

#endif  /* LICENSE_H */
