/* Auto-generated by cbindgen. Do not edit manually. */

#ifndef LICENSE_H
#define LICENSE_H

#pragma once

/* Warning: this file is generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t keypair_generate(uint8_t *public_key_out,
                         uintptr_t public_out_len,
                         uintptr_t *public_written,
                         uint8_t *private_key_out,
                         uintptr_t private_out_len,
                         uintptr_t *private_written);

#endif  /* LICENSE_H */
